services:
  web:
    build: .

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Password1.
  
  caddy:
    image: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    depends_on:
      - web
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile