version: '3.8'

services:
  web:
    build: .
    container_name: web
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"

  db:
    image: postgres
    container_name: assignment_5_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password1.

  caddy:
    image: caddy
    container_name: caddy_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - web
    depends_on:
      - web

networks:
  web:
    driver: bridge
